name: Deploy to Hugging Face Spaces

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout kode
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Push ke Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git remote add huggingface https://adityaUHU:$HF_TOKEN@huggingface.co/spaces/adityaUHU/job-driver
          git push huggingface main --force
